.github/workflows/workflow.yml
src/problems/problems091to100/Problem99.java
test/utils/dates/DatesTest.java

Add/Fix [Solution / Library / Test] for [content here].
Changes in detail here, if applicable

Update Workflow to handle branches and pull requests correctly

---

.github/workflows/workflow.yml
src/ProblemN.java
src/problems/BUILD
src/problems/problems001to010/Problem1.java
src/problems/problems001to010/Problem2.java
src/problems/problems001to010/Problem3.java
src/utils/generators/consumers/GeneratorConsumer.java
test/generate_tests.bzl
test/problems/problems001to010/Problems1to10Test.java

- These serve as additional test cases for our utils
- These also help make sure utils grow more rather than less robust over time

Start adding tests that our solutions still work

---

src/problems/problems001to010/Problem3.java
src/utils/primes/Primes.java
test/problems/problems001to010/Problems1to10Test.java

Enable test case for Problem 3

Make implementation of Factor more efficient

---

src/problems/problems001to010/Problem4.java
test/problems/problems001to010/Problems1to10Test.java

Test for Problem 4 solution

---

src/problems/problems021to030/Problem21.java
src/problems/problems021to030/Problem23.java
src/problems/problems021to030/Problem24.java
src/problems/problems021to030/Problem25.java
src/problems/problems021to030/Problem26.java
src/problems/problems021to030/Problem29.java
src/problems/problems021to030/Problem30.java
test/problems/problems021to030/Problems21to30Test.java

Continue adding test cases for previously solved problems. 
In this PR, add cases for problems in range 21-30 that use util classes.

Tests for problems in [21, 30]

---

src/problems/problems031to040/Problem32.java
src/problems/problems031to040/Problem33.java
src/problems/problems031to040/Problem34.java
src/problems/problems031to040/Problem35.java
src/problems/problems031to040/Problem36.java
src/problems/problems031to040/Problem38.java
src/problems/problems031to040/Problem39.java
src/utils/numbers/BigNumber.java
src/utils/numbers/Rational.java
src/utils/primes/PrimeFactorization.java
test/problems/problems031to040/Problems31to40Test.java

- Optimization in BigNumber factories not to make defensive copies.
- Further optimizations in some problem solutions to reduce runtime.

Add tests for 31 to 40 solutions

---

src/problems/problems051to060/Problem57.java
src/problems/problems071to080/Problem77.java

Solutions for Problems 57 and 77

Solutions for Problems 57 and 77

---

src/problems/problems071to080/Problem73.java
src/problems/problems081to090/Problem87.java
src/utils/numbers/NumericUtils.java
test/utils/numbers/NumericUtilsTest.java

Solutions to 73 and 87

---

src/utils/primes/Primes.java

Minor optimizations for Factor

---

src/problems/problems061to070/Problem69.java
src/utils/primes/PrimeFactorization.java
test/utils/primes/PrimeFactorizationTest.java

Solution to Problem 69

---

src/utils/linalg/Matrix.java
test/utils/linalg/MatrixTest.java

Implementation of Matrix class with multiplication

---

src/problems/problems051to060/Problem55.java
src/problems/problems061to070/Problem63.java

Solutions to 55 and 63

---

src/problems/problems091to100/Problem92.java

Co-authored-by: nkprasad12 <nkprasa@gmail.com>
Add Solution for Problem 92.
Changes in detail here, if applicable

Problem 92 solution

---

src/Sandbox.java
src/problems/problems411to420/Problem420.java

- Tested and finds correct values for N = 50, 100, 1000
- Computes the value for N = 100000 in under 3 seconds
- Needs some much smarter optimization, runtime is N^2

Initial sketch for Problem420

---

src/problems/problems001to100/problems071to080/Problem71.java

Solution to Problem 71

---

src/problems/problems001to100/problems061to070/Problem65.java
src/problems/problems001to100/problems081to090/Problem89.java

Solution to Problem 65

---

src/problems/problems001to100/problems071to080/Problem76.java

Problem 76

---

src/problems/problems101to200/problems101to110/Problem108.java
src/problems/problems101to200/problems101to110/Problem110.java

- Runs in 3 ms for problem 108 (N = 1000)
- Runs in 12 ms for problem 110 (N = 4000000)
- Runs in 30 ms for N = 4000000000

Solutions to problems 108 and 110

---

src/problems/problems001to100/problems061to070/Problem62.java

Solution to Problem62

---

src/problems/problems201to300/problems201to210/Problem206.java

Adds a small workaround to avoid using BigNumber.

Faster solution to Problem 206 (20 s -> 100 ms)

---

src/problems/problems001to100/problems081to090/Problem85.java

Solution to Problem 85

---

src/problems/problems101to200/problems101to110/Problem109.java

Solution to Problem 109

---

src/problems/problems001to100/problems071to080/Problem78.java

Co-authored-by: phenicie@princeton.edu <phenicie@princeton.edu>

Ideas for Problem 78

---

src/problems/problems001to100/problems051to060/Problem51.java

Solution to Problem 51
